### ISSUE TITLE
(kbd "<tab>") does not bind to TAB in terminal

### ISSUE THREAD

**Issue by rnkn** [bmag/imenu-list#18] opened 2016-02-01 05:04 UTC
After noticing that `backtab` is bound to `previous-line` I found it odd that `TAB` isn't bound to `next-line`.

But... then I saw it is bound to `<tab>` in the mode map. It's just that `<tab>` does not translate to `TAB` in terminal mode, only when using the GUI. Using `C-i` for tab (and `C-m` for RET) works pretty reliably.

**Comment by bmag** [comment] 2016-02-01 17:19
Thanks for the report. I don't remember if I had a reason for using `<tab>` and not `TAB`. Before deciding on the change, I want to check if binding `TAB` will have any effect on non-terminal users that want to use `C-i` and `tab` for different commands. I'll work on it on Wednesday.

**Comment by rnkn** [comment] 2016-02-02 02:38
Looks like the [Emacs Manual](https://www.gnu.org/software/emacs/manual/html_node/emacs/Named-ASCII-Chars.html) has the straight story... Looks like ttys don't understand `<tab>` but do understand `C-i`, so Emacs translated `TAB` appropriately...

> If you do not want to distinguish between (for example) `TAB` and `C-i`, make just one binding, for the ASCII character `TAB` (octal code 011). If you do want to distinguish, make one binding for this ASCII character, and another for the “function key” `tab`.

Hence `<tab>` only works on GUI. But `<backtab>` is another story. The following will work reliably on everything:

``` elisp
(defvar imenu-list-major-mode-map
  (let ((map (make-sparse-keymap)))
    ...
    (define-key map (kbd "TAB") #'next-line)
    (define-key map (kbd "<S-iso-lefttab>") #'previous-line)
    (define-key map (kbd "<S-tab>") #'previous-line)
    (define-key map (kbd "<backtab>") #'previous-line)
    ...
    map))
```

**Comment by bmag** [comment] 2016-02-03 14:23
Should be fixed now, thank you.
I'm not a 100% sure I prefer `TAB` to `<tab>`, because I'm not sure how it affects users that use `<tab>` and `C-i` for different stuff (specifically - users that also use evil-jumper), but for now I'm going with `TAB`.
The fix should be available from MELPA within a few hours. If the issue isn't fixed, feel free to reopen it.

**Closed as completed by bmag** 2016-02-03 14:23 UTC

**Comment by rnkn** [comment] 2016-02-04 04:39
Ah cool. Don't worry about `TAB` overwriting `C-i`, it will only translate through if there's not already a mapping on `C-i`.
