### ISSUE TITLE
Imenu list unexpected hide

### ISSUE THREAD

**Issue by consciencia** [bmag/imenu-list#38] opened 2018-01-21 23:51 UTC
After I type <escape> for three times (in different buffer, not in imenu list), imenu list simply hides. How to disable this behavior?

**Comment by bmag** [comment] 2018-01-22 05:50
Not sure what you mean, imenu-list doesn't have an "automatic hide" feature. Please give more details.

**Comment by consciencia** [comment] 2018-01-28 17:58
Actually, I found that imenu-list window was killed by keyboard-escape-quit window killing feature, so, as a workaround, I monkey patched keyboard-escape-quit to not close any windows.

I tried to find how this behavior is bypassed by neotree (which survives keyboard-escape-quit) but failed.

**Comment by bmag** [comment] 2018-01-29 09:29
imenu-list doesn't handle `keyboard-escape-quit` in any special way, so it would seem what you are experiencing is the expected behavior of `keyboard-escape-quit`. I'm closing this as "not a bug".

As for how Neotree differs, you didn't provide nearly enough details, so I can't help you with it.

**Closed as completed by bmag** 2018-01-29 09:29 UTC
Labels: bug
